import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";
import http from "http";
import https from "https";

dotenv.config();

// Helper to perform the self-ping safely
function pingService(url: string) {
  const client = url.startsWith("https") ? https : http;
  client.get(url, (res) => {
    console.log(`[Keep-Warm] Self-ping successful! Status code: ${res.statusCode}`);
  }).on("error", (err) => {
    console.error("[Keep-Warm] Error during self-ping warmup:", err.message);
  });
}

async function startServer() {
  const app = express();
  const PORT = process.env.PORT ? parseInt(process.env.PORT, 10) : 3000;

  // Middleware to parse JSON payloads
  app.use(express.json({ limit: "10mb" }));

  // Initialize Gemini SDK with telemetry User-Agent header
  const geminiApiKey = process.env.GEMINI_API_KEY;
  const ai = geminiApiKey
    ? new GoogleGenAI({
        apiKey: geminiApiKey,
        httpOptions: {
          headers: {
            "User-Agent": "aistudio-build",
          },
        },
      })
    : null;

  // Endpoint to check server status and keep it warm
  app.get("/api/ping", (req, res) => {
    res.json({ status: "alive", timestamp: new Date().toISOString() });
  });

  // Endpoint to generate explanation, notes, questions, concepts
  app.post("/api/generate", async (req, res) => {
    try {
      const { notes } = req.body;
      if (!notes || notes.trim().length === 0) {
        return res.status(400).json({ error: "Study notes are required." });
      }

      if (!ai) {
        return res.status(503).json({
          error: "Gemini API key is not configured. Please add GEMINI_API_KEY to your Secrets panel in AI Studio.",
        });
      }

      // Analyze notes and generate Apple-grade academic insights
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: `Analyze these study notes and generate highly structured premium materials:
        
        """
        ${notes}
        """`,
        config: {
          systemInstruction: "You are an elite, Apple-grade, world-class educator and academic designer. Your tone is sophisticated, extremely clear, smart, instructive, and premium. Format complex elements like equations, bullet lists, or key terms cleanly. Ensure your simpleExplanation is beautiful, engaging and clear. Ensure points in revisionNotes are precise, concise, and dense. Create exactly 4 importantQuestions with clear answers. Terminology definitions in keyConcepts must be pristine and professional.",
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              simpleExplanation: {
                type: Type.STRING,
                description: "Plain English summary, extremely accessible yet sophisticated, explained using an intuitive analogy if appropriate."
              },
              revisionNotes: {
                type: Type.ARRAY,
                items: { type: Type.STRING },
                description: "List of core, dense facts or points summarizing the main document."
              },
              importantQuestions: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    question: { type: Type.STRING },
                    answer: { type: Type.STRING }
                    },
                  required: ["question", "answer"]
                },
                description: "Array of premium review Q&As."
              },
              keyConcepts: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    concept: { type: Type.STRING },
                    definition: { type: Type.STRING }
                  },
                  required: ["concept", "definition"]
                },
                description: "The core terminology with rich but concise definitions."
              }
            },
            required: ["simpleExplanation", "revisionNotes", "importantQuestions", "keyConcepts"]
          }
        }
      });

      const responseText = response.text;
      if (!responseText) {
        return res.status(500).json({ error: "No response text was generated by the AI." });
      }

      const decoded = JSON.parse(responseText.trim());
      res.json(decoded);
    } catch (error: any) {
      console.error("Error during generation service call:", error);
      res.status(500).json({ error: error.message || "An unexpected generation error occurred." });
    }
  });

  // Integration with Vite dev server (development) or serving static build (production)
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server launched successfully on port ${PORT}`);

    // Auto Keep-Warm Self-Pinger for Render Free Tier
    const externalUrl = process.env.RENDER_EXTERNAL_URL;
    if (externalUrl) {
      console.log(`[Keep-Warm] Initializing self-pinger task for ${externalUrl}`);
      // Send a warm up request every 10 minutes to prevent container sleep
      const TEN_MINUTES = 10 * 60 * 1000;
      setInterval(() => {
        pingService(`${externalUrl}/api/ping`);
      }, TEN_MINUTES);
    } else {
      console.log("[Keep-Warm] RENDER_EXTERNAL_URL env is not set. Specify your deployment URL in Render to activate auto self-pinger.");
    }
  });
}

startServer();
